### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by jwyglendowski-precisionlender** [brunojppb/node-distributed-lock#1]
Thanks for sharing this code and blog post. Just curious any plans on putting a license on this code?

**Comment by brunojppb** [comment]
Happy you found this useful, @jwyglendowski-precisionlender 🙌

I've just addressed this here and you should be able to use this code under the MIT license: https://github.com/brunojppb/node-distributed-lock/commit/2bc997e1c3356f5c6a6c943a3d2c5bb984484490

**Comment by jwyglendowski-precisionlender** [comment]
@brunojppb Thanks that is very much appreciated.
